# Generated by Django 3.2.9 on 2022-05-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('uncategorized', 'Uncategorized'), ('additive', 'Additive'), ('animal-product', 'Animal Product'), ('bakery', 'Bakery'), ('berry', 'Berry'), ('beverage-alcoholic', 'Beverage Alcoholic'), ('beverage-caffeinated', 'Beverage Caffeinated'), ('beverage', 'Beverage'), ('cabbage', 'Cabbage'), ('cereal', 'Cereal'), ('dairy', 'Dairy'), ('dish', 'Dish'), ('essential-oil', 'Essential Oil'), ('fish', 'Fish'), ('flower', 'Flower'), ('fruit-citrus', 'Fruit Citrus'), ('fruit-essence', 'Fruit Essence'), ('fruit', 'Fruit'), ('fungus', 'Fungus'), ('gourd', 'Gourd'), ('herb', 'Herb'), ('legume', 'Legume'), ('maize', 'Maize'), ('meat', 'Meat'), ('nut', 'Nut'), ('plant-derivative', 'Plant Derivative'), ('plant', 'Plant'), ('seafood', 'Seafood'), ('seed', 'Seed'), ('spice', 'Spice'), ('vegetable-fruit', 'Vegetable Fruit'), ('vegetable-root', 'Vegetable Root'), ('vegetable-stem', 'Vegetable Stem'), ('vegetable-tuber', 'Vegetable Tuber'), ('vegetable', 'Vegetable')], default='uncategorized', max_length=30, verbose_name='category')),
                ('flavordb_id', models.PositiveIntegerField(help_text='ID of the corresponding entity in the FlavorDB database.', unique=True, verbose_name='FlavorDB ID')),
            ],
            options={
                'verbose_name': 'ingredient',
                'verbose_name_plural': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='IngredientName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', related_query_name='name', to='ingredients.ingredient', verbose_name='ingredient')),
            ],
            options={
                'verbose_name': 'ingredient name',
                'verbose_name_plural': 'ingredient names',
            },
        ),
        migrations.CreateModel(
            name='IngredientMolecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecule_pubchem_id', models.PositiveIntegerField(help_text='ID of the molecule in the PubChem database.', verbose_name='molecule PubChem ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molecule_entries', related_query_name='molecule_entry', to='ingredients.ingredient', verbose_name='ingredient')),
            ],
        ),
    ]
