# Generated by Django 3.2.9 on 2022-05-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientmolecule',
            name='molecule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_entries', related_query_name='ingredient_entry', to='ingredients.molecule', verbose_name='molecule'),
        ),
    ]
