# Generated by Django 3.2.9 on 2022-05-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20220525_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientname',
            options={'ordering': ['ingredient', 'priority'], 'verbose_name': 'ingredient name', 'verbose_name_plural': 'ingredient names'},
        ),
        migrations.AddField(
            model_name='ingredientname',
            name='priority',
            field=models.SmallIntegerField(default=100, help_text='Items with lower values here will come first.', verbose_name='priority'),
        ),
    ]
