# Generated by Django 3.2.9 on 2022-05-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_auto_20220525_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='foodb_internal_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Internal FooDB ID'),
        ),
        migrations.AddField(
            model_name='molecule',
            name='foodb_internal_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Internal FooDB ID'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(condition=models.Q(('foodb_id', ''), _negated=True), fields=('foodb_internal_id',), name='foodb_internal_food_ids_unique'),
        ),
        migrations.AddConstraint(
            model_name='molecule',
            constraint=models.UniqueConstraint(condition=models.Q(('foodb_id', ''), _negated=True), fields=('foodb_internal_id',), name='foodb_internal_molecule_ids_unique'),
        ),
    ]
