# Generated by Django 3.2.9 on 2022-05-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_auto_20220525_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientmolecule',
            name='foodb_content_sample_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of samples were summed up in the other FooDB parameter. This is used to calculate an average.', verbose_name='FooDB sample size'),
        ),
        migrations.AddField(
            model_name='ingredientmolecule',
            name='foodb_content_sum',
            field=models.FloatField(default=0.0, help_text='Sum of content values from FooDB. These indicate how much of the molecule was found (in mg / 100g).', verbose_name='FooDB content sum'),
        ),
    ]
