# Generated by Django 3.2.9 on 2022-05-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_auto_20220525_1544'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='foodb_internal_food_ids_unique',
        ),
        migrations.RemoveConstraint(
            model_name='molecule',
            name='foodb_internal_molecule_ids_unique',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='foodb_internal_id',
        ),
        migrations.RemoveField(
            model_name='molecule',
            name='foodb_internal_id',
        ),
        migrations.AlterField(
            model_name='molecule',
            name='pubchem_id',
            field=models.PositiveIntegerField(default=None, help_text='ID of the molecule in the PubChem database.', null=True, verbose_name='PubChem ID'),
        ),
        migrations.AddConstraint(
            model_name='molecule',
            constraint=models.UniqueConstraint(condition=models.Q(('pubchem_id__isnull', False)), fields=('pubchem_id',), name='pubchem_ids_unique'),
        ),
        migrations.AddConstraint(
            model_name='molecule',
            constraint=models.CheckConstraint(check=models.Q(('pubchem_id__isnull', False), models.Q(('foodb_id', ''), _negated=True), _connector='OR'), name='molecule_has_identifier'),
        ),
    ]
