# Generated by Django 3.2.9 on 2022-05-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_auto_20220525_1557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientMolecule',
            new_name='MoleculeOccurrence',
        ),
    ]
