# Generated by Django 3.2.9 on 2022-05-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_rename_ingredientmolecule_moleculeoccurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moleculeoccurrence',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molecule_occurrences', related_query_name='molecule_occurrence', to='ingredients.ingredient', verbose_name='ingredient'),
        ),
        migrations.AlterField(
            model_name='moleculeoccurrence',
            name='molecule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', related_query_name='occurrence', to='ingredients.molecule', verbose_name='molecule'),
        ),
    ]
